name: Santest
on: push

jobs:
  build:
    name: santest first I 


jobs:
  build:
    name: Hello world action

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"

      - name: run test 
        run: echo test san


