name: Santest
on: push

jobs:
  build:
    name: santest first I 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
                env: 
                  TEST_ENV1= ${{ secrets.TEST_ENV }}  
                MY_NAME: "$TEST_ENV1"

      - name: run test 
        run: echo test san


